### PR TITLE
Change cloudinit merge order

### PR DESCRIPTION
**Pull request by futuretea**
change the merge order
merge d.CloudConfig in the end

**Related issues**
https://github.com/harvester/harvester/issues/3855

**Test plan**
1. Go to the Rancher UI and click `Cluster Management` > `Drivers` > `Node Drivers`. In the `Node Drivers` list, find ` Harvester` and then click `⋮`  > `View in API`.
2. Click `Edit`.
3. Uncheck the `builtin` checkbox.
4. Change the `*url` to `https://github.com/futuretea/docker-machine-driver-harvester/releases/download/v0.0.0-ce551fc/docker-machine-driver-harvester-amd64.tar.gz`.
5. Change the `checksum` to `33ab8006ed03c1eaf77d1d0dbbb7c8bd3f7d2ceb60fadc3fbcea237faf88f6dc`.
6. Click `Show Request` > `Send Request`.
7. Click `Reload` util the value of `status.appliedChecksum` and `status.appliedURL` change to the value we set.
8. Use Harvester node driver to provision a RKE2 cluster
9. Check the created VM's cloud config userdata

In the runcmd section, the injected part `sh /usr/local/custom_script/install.sh ` was injected at beginning.

### CODE REVIEW

**Review by guangbochen — COMMENTED** [review]
can we add a unit test to validate it, thanks.

**Comment by futuretea** [comment]
> can we add a unit test to validate it, thanks.

Added

**Review by guangbochen — APPROVED** [review]
LGTM, thanks.

**Review by ibrokethecloud — APPROVED** [review]

**Comment by ibrokethecloud** [comment]
LGTM. Can confirm that the order reflects correctly in the merged cloud-init

**Pull request merged**
