### PR TITLE
Add UnmarshalJSON hook

### PR DESCRIPTION
**Pull request by m-ildefons**
Add the UnmarshalJSON hook analogue to https://github.com/rancher/machine/pull/224/files#diff-0af55c3724f49cec74fe33467f9431bd1298302cd6cb9d97c96fb5919ab910a0

This hook allows the rancher machine driver to pass a JSON object with the driver config. In case config options have been updated, the new values can be passed via command line on driver invokation, which overrides the values from the JSON config, for some config options.

~This PR is a draft, because it still needs to be validated that this fixes the issue satisfactory.~

related-to: https://github.com/rancher/machine/pull/224
related-to: https://github.com/rancher/rancher/issues/44912#issuecomment-2253177277

Signed-off-by: Moritz Röhrich <moritz.rohrich@suse.com>

### CODE REVIEW

**Comment by m-ildefons** [comment]
@jakefhyde Unfortunately, I can't put you down as a reviewer, since you're not member of the Harvester organization on GitHub. Nevertheless, I'd be super grateful, if you could take a look at this.

**Review by jakefhyde — APPROVED** [review]
LGTM!

**Comment by m-ildefons** [comment]
I've confirmed that this fixes the [problem reported by the user](https://github.com/rancher/rancher/issues/44912#issuecomment-2253177277)
To do this, I did the following:

I replaced the harvester node driver binary in the Rancher container. Then I made sure that all cloud-credentials were expired and applied the workaround from the KB-article, rotating the cloud-credentials.
After confirming that the new harvester node driver binary was indeed being served at `https://rancher.[redacted].sslip.io/assets/docker-machine-driver-harvester`, I edited the cluster config, changing the memory spec for the VMs from 6GiB to 4GiB. This caused a re-provisioning of the VMs using the now new harvester node driver binary.
The re-provisioning eventually completed successfully with the old nodes correctly removed, indicating that the rotated credentials are indeed propagated correctly to the harvester node driver.

**Review by FrankYang0529 — APPROVED** [review]
LGTM. Thanks for the PR.

**Pull request merged**
